# server配置
server:
  port: 8800
  tomcat:
    uri-encoding: UTF-8
  servlet:
    context-path: /core

# spring配置
spring:
  application:
    name: core
  cloud:
    nacos:
      discovery:
        server-addr: nacos.ulitom.com:8848
        enabled: true

  # 连接池
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://127.0.0.1:3306/zhuzs?useUnicode=true&characterEncoding=utf-8&useSSL=false&autoReconnect=true&allowMultiQueries=true&failOverReadOnly=false&allowPublicKeyRetrieval=true
      username: root
      password: Root1234@
      initial-size: 5
      min-idle: 5
      max-active: 200
      max-wait: 6000
      time-between-eviction-runs-millis: 28000  # 需要小于mysql的wait_timeout
      min-evictable-idle-time-millis: 300000
      validation-query: select 1 from dual
      test-while-idle: true
      test-on-borrow: true
      test-on-return: true
      poolPreparedStatements: true
      maxPoolPreparedStatementPerConnectionSize: 20
      logAbandoned: true
      removeAbandoned: false
      removeAbandonedTimeout: 1800
      removeAbandonedTimeoutMillis: 1800000
      filters: stat,slf4j,default #去掉wall，因为增加wall导致不能sql批量更新操作
      web-stat-filter:
        enabled: true
        url-pattern: /*
        exclusions: "*.js,*.gif,*.jpg,*.bmp,*.png,*.css,*.ico,/druid/*"
      filter:
        stat:
          enabled: true
          merge-sql: true
          slow-sql-millis: 3000
          log-slow-sql: true
          db-type: mysql
        slf4j:
          enabled: true
          statement-create-after-log-enabled: false
          statement-log-enabled: false
          statement-executable-sql-log-enable: true
          statement-log-error-enabled: true
          result-set-log-enabled: false

  # redis
  redis:
    #redis服务器地址
    host: localhost
    port: 6379
    password:
    database: 0
    #redis连接超时时间（毫秒）
    timeout: 18000
    #lettuce连接池配置 springboot2.x后默认使用Lettuce:
    #lettuce:
    jedis:
      pool:
        # 连接池最小空闲连接
        min-idle: 1
        # 连接池最大空闲连接
        max-idle: 5
        # 连接池最大连接数（使用负值表示没有限制）
        max-active: 8
        # 连接池最大空闲连接（使用负值表示没有限制）
        max-wait: -1

# MyBatisPlus 配置
#mybatis-plus:
#  # 映射文件所在路径
#  mapper-locations: classpath*:mapper/*.xml
#  typeAliasesPackage: com.zhuzs.admin.entity.domain
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

mybatis:
  type-aliases-package: com.example.springboottaskcore.entity.domain
  mapper-locations: classpath*:/mapper/*.xml

# nacos 配置
#nacos:
#  config:
#    server-addr: 127.0.0.1:8848
# swagger ui
swagger:
  enabled: true

# 防止 druid 的错误 log 打印
druid:
  mysql:
    usePingMethod: false


# 日志记录
logging:
  config: classpath:logback.xml

########################################################################################################################

file:
  path: ../file/upload/

  # file:
  #  path: /Users/zhuzs/Downloads/download/tempory
